/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 14 18:55:01 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.AssumptionViolatedException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PairProgram_ESTest extends PairProgram_ESTest_scaffolding {


public static void main(String[] args) throws Throwable {
test0();
test1();


test2();
test3();
}

  @Test(timeout = 4000)
  public static void test0()  throws Throwable  {
      int[] intArray0 = new int[4];
      List list0 = PairProgram.listgen(intArray0);
      PairProgram pairProgram0 = new PairProgram();
      pairProgram0.OldIsValueAtEnd = false;
      pairProgram0.OldIsValueAtEnd = true;
      // Undeclared exception!
      try { 
        pairProgram0.TestStudentSubmission(list0, 1);
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public static void test1()  throws Throwable  {
      PairProgram pairProgram0 = new PairProgram();
      int[] intArray0 = new int[3];
      pairProgram0.OldIsLengthOdd = true;
      List list0 = PairProgram.listgen(intArray0);
      // Undeclared exception!
      try { 
        pairProgram0.TestStudentSubmission(list0, 0);
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public static void test2()  throws Throwable  {
      PairProgram pairProgram0 = new PairProgram();
      List list0 = new List();
      List list1 = new List(2072);
      list0.next = list1;
      pairProgram0.safe = true;
      // Undeclared exception!
      try { 
        pairProgram0.TestStudentSubmission(list0, 0);
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public static void test3()  throws Throwable  {
      PairProgram pairProgram0 = new PairProgram();
      List list0 = new List(0);
      // Undeclared exception!
      try { 
        pairProgram0.TestStudentSubmission(list0, 0);
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public static void test4()  throws Throwable  {
      int[] intArray0 = new int[0];
      List list0 = PairProgram.listgen(intArray0);
      assertEquals(0, list0.value);
  }

  @Test(timeout = 4000)
  public static void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        PairProgram.listgen((int[]) null);
      
      } catch(AssumptionViolatedException e) {
         //
         // got: <false>, expected: is <true>
         //
      }
  }

  @Test(timeout = 4000)
  public static void test6()  throws Throwable  {
      List list0 = new List();
      list0.next = list0;
      PairProgram pairProgram0 = new PairProgram();
      // Undeclared exception!
      try { 
        pairProgram0.TestStudentSubmission(list0, 0);
      
      } catch(AssumptionViolatedException e) {
         //
         // got: <false>, expected: is <true>
         //
      }
  }

  @Test(timeout = 4000)
  public static void test7()  throws Throwable  {
      PairProgram pairProgram0 = new PairProgram();
      // Undeclared exception!
      try { 
        pairProgram0.TestStudentSubmission((List) null, 0);
      
      } catch(AssumptionViolatedException e) {
         //
         // got: <false>, expected: is <true>
         //
      }
  }
}
